[package]
name = "v2ray-geoip"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
description = "V2Ray subscription fetcher with geo localization functionality"
readme = "README.md"
repository = "https://github.com/nikodemin/v2ray_geoip"
authors = ["Nikita Dyomin"]

[package.metadata.wix]
upgrade-guid = "4EF0FE7E-CF1C-4960-A73D-0DCAC59E963B"
path-guid = "C6DA6C1F-F2DC-4E27-971B-058C485F9248"
license = false
eula = false

[dependencies]
ping = { version = "0.9.0" , features = ["tokio"]}
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
log = "0.4"
pretty_env_logger = "0.5"
serde = { version = "1.0.229" , features = ["derive"]}
config = "0.15.25"
clokwerk = { version = "0.4.0" , features = ["async"]}
log4rs = "1.4.0"
axum = { version = "0.8.9", features = ["macros"]}
reqwest = { version = "0.13.5", features = ["json"]}
regex = "1.13.1"
tokio-stream = "0.1.19"
futures = "0.3.34"
tokio-rusqlite = { version = "0.8.0" ,features = ["bundled", "chrono"]}
dns-lookup = "4.0.1"
proptest = "1.11.0"
rand = "0.9.5"
base64 = "0.23.1"
serde_json = "1.0.151"
reqwest-retry = "0.9.1"
reqwest-middleware = { version = "0.5.2" , features = ["json"]}

[profile.dist]
inherits = "release"
lto = "thin"