sub_groups=["https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/Sub1.txt", "https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/Sub2.txt"]
geo_base_url="http://ip-api.com"
batch_size=20
recheck_period="30 s"
update_period="30 s"
